---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: eshoponweb-dev
  namespace: argocd
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: https://github.com/manunio/k8s-cluster.git
=======
    repoURL: https://gitlab.com/max1832/k8s-cluster.git
>>>>>>> c2d06a38c35144db7668e189cadd323b48d23228
    targetRevision: HEAD
    path: dev/helm/eshoponweb
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshoponweb-prod
  namespace: argocd
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: https://github.com/manunio/k8s-cluster.git
=======
    repoURL: https://gitlab.com/max1832/k8s-cluster.git
>>>>>>> c2d06a38c35144db7668e189cadd323b48d23228
    targetRevision: HEAD
    path: prod
  destination:
   server: https://kubernetes.default.svc
   namespace: prod
  syncPolicy:
    automated:
      prune: true

