---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: eshoponweb-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/manunio/k8s-cluster.git
    targetRevision: HEAD
    path: dev/helm/eshoponweb
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshoponweb-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/manunio/k8s-cluster.git
    targetRevision: HEAD
    path: prod
  destination:
   server: https://kubernetes.default.svc
   namespace: prod
  syncPolicy:
    automated:
      prune: true

