replicaCount: 1
clusterName: eshoponweb-k8s
pathBase: /webmvc
image:
  repository: eshop/webmvc
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  tls: []

registry:                # Uncomment "registry" to specify registry secret
  secretName:            # secretName is the name of the secret inside k8s   

svc:
  mvc:

k8s:                      # inf.k8s defines Kubernetes cluster global config
  dns:  ""                # k8s external  DNS. This value or ip value MUST BE PROVIDED
  local: false  
resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: UseLoadTest
      key: all_EnableLoadTest
    - name: DPConnectionString
      key: webmvc__keystore
    - name: PurchaseUrl
      key: internalurls__apigwws
    - name: ExternalPurchaseUrl
      key: urls__apigwws
    - name: CallBackUrl
      key: urls__mvc
    - name: IdentityUrl
      key: urls__IdentityUrl
    - name: MarketingUrl
      key: internalurls__apigwwm
    - name: IdentityUrlHC
      key: internalurls__identity__hc      
    - name: SignalrHubUrl
      key: urls__apigwws
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'