{{- if .Values.ingress.enabled -}}
{{- $ingressPath := include "pathBase" . -}}
{{- $serviceName := .Values.svc.mvc -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "eshoponweb.fullname" . }}
  labels:
    app: {{ template "eshoponweb.name" . }}
    chart: {{ template "eshoponweb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: 8080
  {{- end }}
{{- end }}