apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgBTqxP7hnkehGiKZPmrSvKNZ4FjgJdSDYvmk+JoRlR0xvoFGEPos7b1rkMXj7RBkSFE7OLPH7fKQkvdibS7gATsmqG4CyS+5RLC3HxGV7bXhbZGEEmH7to5gBInS0aLfylLETC9N6DUoAWD7ibALl2+OBBgICcPrp71ifA6oGO2ctYBh2MatvRrPA8Ck3CdJLgfFCOAp/Oc3q+SUsctHP5Enow3eYA4IfEhmGjobJWHv6JZ5+BzFUWl37KsKvNOG5unUXRULzxI1+PnANhcZj46Adg8xdTWHwG1555s1QcFVKXqMIhdgLlzsaMVNmbMhFYJxiyKrIzrHUKvOoX2Ypr8NA1Yik+FEaHgev5WA4jDUmcAu8leZhE7xXeIiQqzBY8249RNXeqXcfIrGijfxuRean+Ll1kbgZ+YhNXxv481APdwrwYk2khfHrRmplK7izGWovVIZdYtcDIZWuv3O/bUGCGbxj2y0A908E0AdIUO4mq2olHJ5e4RkFhPtY+nvVnif9UrxqtMEpbu2+xlIclSqBNuJCA+ucFxajPWa4XzVfVwZbWyW8CNmilNQ+m+w+3Mj/kpbpyaRCnCyKUr3vlVcqttgJqvmqR6N0RrCwJcFzdSiwBiD0G2J/h9PcgY+wsdDtdrJE5aoupmvG1miDmx3S2kguechaa+HCTo8AdlwqkWMB3z/hecE/2Ptj6vR8ops4nTsWpmS2OkXBF8B9tAIWm85BsQGb2E5ZZhJ+B3zNvNT+RWnu6vgZYUkwsjWX+sUyJJnfJJrgwZYTRqHb7K9kL3RKvjMAEKOWrOPKtLLIw1ljpOAIIgpVXjUOCTZRep6AJQGyVVUquCubBWETAW71XCnmKZfg6BSAbFWR3nlg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: dev
    type: kubernetes.io/dockerconfigjson

