apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCSw9FhNXlApRCTSrCwehvSwGBHil/kbMVLhpswl1JboSEA13Yqh3lPu//yOeLu9+98OESUSD48uGAZKrl3AFa9VCuc4uDT0V1SedhaKIjR4n5tvQW+DPdTCqU09vnGxytP9LoQ0ZD7ri0+6m7qyIQQCwUEaq5Abg9AHogWWLr4cKSUTXRsvY7r3HRzloJ4hv2+kGhwUs6hOYmlrBazWHVLv6BjhfR7aYNdBtQskL+ypGbJAPn++QdUE3dL6xO9l5G6F5B+3U2Dk/GmxgdUVL+CvnRc96O8C7K+w38vE42sLHUWjHs13+VYxKg5Ur/Ip0oQqNwIo80W4VWnPbvESt8gQyl+m3CqViOH7NNocnluXdcGyqsbYnRGwNDkPHAxLIWqqQAswuxteaGql5gKJvKz+nqufr26O8HhhuOTtsu0oJCnA6JNDy/KtFJ3JPYlC2UpRM/NzoSiQuErlm6pfCWm6Nwqcc6OV3ztjORJN/ZZU7BCupY0f9Ee15kkSlKAeXL/tdFuFtX6RINoF0mNn4NmMxorlIiCkV/b/pP1ht5/IoFOrei9OXlSop4J1C2/SxhlEjqYB31fA7V2DJnMSkizspDVyQ2JIlTntGZNozltEhWIP0TpB5QghGUmeUrsdg4n8L4b3OyZSgNKD3HmuD6PXtMnN3lwgHOru8fJ5zu4zRO0HGd6vJqI6wsUZSSWeLQC6myspb046SaJNBYlBuN/vpaa7QLHECAM6AbOPIbfNihUg1clLk0GrPUZa816//D7EJsPvtRRJXqvgACUGd7jntXTndP7S9gYL/s73tN5vp3045qVALbsC4dwddGF4VEBAH0Fzpq62FWhcATUIpzfHCOG7jxafmIyRE3rB2StPw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: dev
    type: kubernetes.io/dockerconfigjson

